language: ruby
rvm:
  - 2.0.0-p247
branches:
  only:
  - source
before_install:
- openssl aes-256-cbc -K $encrypted_cc8a248765f4_key -iv $encrypted_cc8a248765f4_iv
  -in .travis/deploy.enc -out ~/.ssh/deploy -d
# set the permission of the key
- chmod 600 ~/.ssh/deploy
# Start SSH agent 
- eval $(ssh-agent)
# Add the private key to the system 
- ssh-add ~/.ssh/deploy
# Copy SSH config 
- cp .travis/ssh_config ~/.ssh/config
# Set Git config
- git config --global user.name "matrixbot"
- git config --global user.email matrix.orz@gmail.com
- git config --global push.default simple
- git remote -v
- git fetch --all
- git checkout -b master
install:
- gem install jekyll
- gem install jekyll-paginate
- gem install jekyll-gist
script:
- jekyll build >log.txt
#after_script:
- cat log.txt
- git add -A 
- git commit -m "Modified by travis build"
#- git status>status.txt
#- less status.txt
- git push -f --repo git@github.com:matrixorz/matrixorz.github.io.git     
